</div><!-- /.container-fluid -->
</section>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->




<footer class="main-footer">
<strong>Copyright &copy; 2014-2019 <a href="#">NCI</a>.</strong>
All rights reserved.
<div class="float-right d-none d-sm-inline-block">
  <!-- <b>Version</b> 3.0.5 -->
</div>
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
<!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->




<!-- jQuery -->
<script src="../refer/template/plugins/jquery/jquery.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="../refer/template/plugins/jquery-ui/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
$.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="../refer/template/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- daterangepicker -->
<script src="../refer/template/plugins/daterangepicker/moment.min.js"></script>
<script src="../refer/template/plugins/daterangepicker/daterangepicker.js"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="../refer/template/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
<!-- Summernote -->
<!-- <script src="../include/template/plugins/summernote/summernote-bs4.min.js"></script> -->
<!-- overlayScrollbars -->
<!-- <script src="../refer/template/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script> -->
<!-- AdminLTE App -->
<script src="../refer/template/dist/js/adminlte.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<!-- <script src="../include/template/dist/js/pages/dashboard.js"></script> -->
<!-- AdminLTE for demo purposes -->
<!-- <script src="../include/template/dist/js/demo.js"></script> -->
<!-- DataTables -->
<script src="../refer/template/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="../refer/template/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="../refer/template/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="../refer/template/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<!-- Toastr -->
<script src="../refer/template/plugins/toastr/toastr.min.js"></script>
<!-- jquery-validation -->
<script src="../refer/template/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="../refer/template/plugins/jquery-validation/additional-methods.min.js"></script>

