<html>
<head>
<link rel="stylesheet" type="text/css" href="../../include/AdminLTE-3.0.5/dist/css/adminlte.css">
<link rel="stylesheet" type="text/css" href="../../include/AdminLTE-3.0.5/dist/css/adminlte.css.map">
<link rel="stylesheet" type="text/css" href="../include/AdminLTE-3.0.5/dist/css/adminlte.min.css">
<link rel="stylesheet" type="text/css" href="../include/AdminLTE-3.0.5/dist/css/adminlte.min.css.map">
<!-- jQuery -->
<script src="../../include/AdminLTE-3.0.5/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../../include/AdminLTE-3.0.5/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../../include/AdminLTE-3.0.5/dist/dist/js/adminlte.min.js"></script>
<style>
/* .header{
    background-position-x: left;
    background-image: url("../../app/images/head_logo.png");
    background-repeat: no-repeat;
    display: inline-block;
    text-align: center;
    width: 75%;
}
.header h1 {
  text-align: center;
  position: relative;
  left: 10px;
  margin-left : 400px;
   margin-bottom: 40px;  
} */
</style>
<div class="text-center">
<h1>WEB在庫・価格管理システム</h1>
</div>
</head>


