<?php  
include_once "common/session.php";
include_once "common/authentication.php"; 
?>
<html>
<head>
<link rel="stylesheet" type="text/css" href="../refer/template/dist/css/adminlte.css">
<link rel="stylesheet" type="text/css" href="../refer/template/dist/css/adminlte.css.map">
<link rel="stylesheet" type="text/css" href="../refer/template/dist/css/adminlte.min.css">
<link rel="stylesheet" type="text/css" href="../refer/template/dist/css/adminlte.min.css.map">

<!-- Font Awesome -->
<link rel="stylesheet" href="../refer/template/plugins/fontawesome-free/css/all.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- jQuery -->
<script src="../refer/template/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="../refer/template/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="../refer/template/dist/js/adminlte.min.js"></script>
<style>
/* .header{
    background-position-x: left;
    background-image: url("../../app/images/head_logo.png");
    background-repeat: no-repeat;
    display: inline-block;
    text-align: center;
    width: 75%;
}
.header h1 {
  text-align: center;
  position: relative;
  left: 10px;
  margin-left : 400px;
   margin-bottom: 40px;  
} */
</style>
<div class="text-center">
<h1>WEB在庫・価格管理システム</h1>
</div>
</head>


